name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust
        run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
      - name: Install latest mdbook
        run: |
          cargo install mdbook
      - name: Install mdbook-mermaid
        run: |
          cargo install mdbook-mermaid
      - name: Build Book-basic
        run: |
          cd docs/book-basic
          mdbook build
      - name: Build Book-CNN
        run: |
          cd docs/book-cnn
          mdbook build
      - name: Prepare public
        run: |
          mkdir -p public
          cp -r docs/book-basic/book public/book-basic
          cp -r docs/book-cnn/book public/book-cnn
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4